import dotenv from 'dotenv';import mongoose from 'mongoose';import bcrypt from 'bcryptjs';
dotenv.config();
const productSchema=new mongoose.Schema({name:String,category:String,purchasePrice:Number,sellingPrice:Number,stockQuantity:Number,reorderLevel:Number,preferredReorderQty:Number,unit:String},{timestamps:true});
const customerSchema=new mongoose.Schema({name:String,phone:String,address:String,creditLimit:Number},{timestamps:true});
const supplierSchema=new mongoose.Schema({name:String,phone:String,address:String},{timestamps:true});
const userSchema=new mongoose.Schema({email:{type:String,unique:true},passwordHash:String,name:String});
const Product=mongoose.models.Product||mongoose.model('Product',productSchema);const Customer=mongoose.models.Customer||mongoose.model('Customer',customerSchema);const Supplier=mongoose.models.Supplier||mongoose.model('Supplier',supplierSchema);const User=mongoose.models.User||mongoose.model('User',userSchema);
await mongoose.connect(process.env.MONGODB_URI);await Product.deleteMany({});await Customer.deleteMany({});await Supplier.deleteMany({});
await Product.insertMany([{name:'Sugar 1kg',category:'Grocery',purchasePrice:150,sellingPrice:180,stockQuantity:18,reorderLevel:5,preferredReorderQty:20,unit:'Pack'},{name:'Tea 190g',category:'Beverages',purchasePrice:320,sellingPrice:380,stockQuantity:4,reorderLevel:5,preferredReorderQty:12,unit:'Pack'},{name:'Cooking Oil 1L',category:'Grocery',purchasePrice:520,sellingPrice:590,stockQuantity:9,reorderLevel:5,preferredReorderQty:10,unit:'Bottle'},{name:'Biscuits',category:'Snacks',purchasePrice:45,sellingPrice:60,stockQuantity:3,reorderLevel:5,preferredReorderQty:20,unit:'Pack'}]);await Customer.insertMany([{name:'Walk-in Customer',phone:'',address:''},{name:'Muhammad Ali',phone:'03001234567',address:'Local Market',creditLimit:5000}]);await Supplier.insertMany([{name:'City Wholesale',phone:'03001112222',address:'Main Bazaar'}]);const hash=await bcrypt.hash('admin123',10);await User.updateOne({email:'admin@abdulrehmanstore.local'},{$set:{email:'admin@abdulrehmanstore.local',passwordHash:hash,name:'Store Owner'}},{upsert:true});console.log('Seed complete. Login: admin@abdulrehmanstore.local / admin123');await mongoose.disconnect();
